---
# Source: url-shortener/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: url-shortener-dev-external-secret
  labels:
    helm.sh/chart: url-shortener-0.1.0
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: url-shortener-dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: resilience-gate-secrets
    kind: ClusterSecretStore
  target:
    name: url-shortener-dev-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        REDIS_URL: "{{ .redis_url }}"
        password: "{{ .database_password }}"
        postgres-password: "{{ .database_password }}"
        redis-password: "{{ .redis_password }}"
        SERVICE_WALLET_ADDRESS: "{{ .service_wallet_address }}"
  data:
    - secretKey: database_url
      remoteRef:
        key: "resilience-gate-dev-url-shortener-database-url"
    - secretKey: database_password
      remoteRef:
        key: "resilience-gate-dev-url-shortener-database-password"
    - secretKey: redis_url
      remoteRef:
        key: "resilience-gate-dev-url-shortener-redis-url"
    - secretKey: redis_password
      remoteRef:
        key: "resilience-gate-dev-url-shortener-redis-password"
    - secretKey: service_wallet_address
      remoteRef:
        key: "resilience-gate-dev-service-wallet-address-testnet"
