---
# Source: url-shortener/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener-dev
  labels:
    helm.sh/chart: url-shortener-0.1.0
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: url-shortener-dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
