---
# Source: url-shortener/charts/redis/templates/master/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: url-shortener-prod-redis-master
  namespace: "url-shortener-prod"
  labels:
    app.kubernetes.io/instance: url-shortener-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 8.6.1
    helm.sh/chart: redis-25.3.5
    app.kubernetes.io/component: master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: url-shortener-prod
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: master
