---
# Source: url-shortener/charts/redis/templates/master/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: url-shortener-dev-redis-master
  namespace: "url-shortener-dev"
  labels:
    app.kubernetes.io/instance: url-shortener-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 8.6.1
    helm.sh/chart: redis-25.3.5
