#!/usr/bin/env bash
# Scoped lifecycle entrypoint for the owned Resilience Gate testnet lab.
# The default is read-only status. Destruction is deliberately difficult and
# never falls back to gcloud or kubectl deletion shortcuts.

set -euo pipefail

LAB_OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "$LAB_OPS_DIR/../platform_setup_scripts" && pwd)"
config_file="${CONFIG_FILE:-$PLATFORM_DIR/config.env}"
command_name="status"
command_set=false
status_scope="all"
apply_requested=false
confirmed_project=""
destruction_acknowledged=false
temporary_dir=""

usage() {
  cat <<'EOF'
Usage: lab-ops.sh [--config PATH] [--scope platform|gitops|gate|all]
                  [--apply --confirm-project PROJECT_ID
                   --acknowledge-owned-testnet-lab-destruction]
                  [status|bootstrap-plan|destroy-plan|destroy]

Commands:
  status          Run read-only Kubernetes verification (default).
  bootstrap-plan  Print the reviewed bootstrap actions with DRY_RUN=true.
  destroy-plan    Produce a read-only Terraform destroy plan with a bounded state lock wait.
  destroy         Apply a freshly generated destroy plan only after explicit
                  flags and an interactive project-ID retype.

`destroy` never disables Terraform deletion protection and never uses gcloud
or kubectl deletion commands. It is intended only for an owned testnet lab.
EOF
}

die() {
  printf '[ERR ] %s\n' "$*" >&2
  exit 1
}

require_option_value() {
  local option="$1"
  if [ "$#" -lt 2 ] || [ -z "${2:-}" ]; then
    printf '[ERR ] %s requires a value\n' "$option" >&2
    exit 2
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --config)
      require_option_value "$@"
      config_file="$2"
      shift 2
      ;;
    --scope)
      require_option_value "$@"
      status_scope="$2"
      shift 2
      ;;
    --apply)
      apply_requested=true
      shift
      ;;
    --confirm-project)
      require_option_value "$@"
      confirmed_project="$2"
      shift 2
      ;;
    --acknowledge-owned-testnet-lab-destruction)
      destruction_acknowledged=true
      shift
      ;;
    status|bootstrap-plan|destroy-plan|destroy)
      if [ "$command_set" = true ]; then
        printf '[ERR ] Specify only one lifecycle command\n' >&2
        exit 2
      fi
      command_name="$1"
      command_set=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf '[ERR ] Unknown option or command: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$status_scope" in
  platform|gitops|gate|all) ;;
  *)
    printf '[ERR ] --scope must be platform, gitops, gate, or all\n' >&2
    exit 2
    ;;
esac

cleanup_temporary_dir() {
  if [ -z "$temporary_dir" ] || [ ! -d "$temporary_dir" ]; then
    return 0
  fi

  # Only a directory generated by this script under the fixed safe location
  # may be removed. Terraform state and plans are never stored in the repo.
  case "$temporary_dir" in
    /tmp/resilience-gate-lab-ops.*)
      rm -rf -- "$temporary_dir"
      ;;
    *)
      printf '[ERR ] Refusing to remove unexpected temporary path: %s\n' "$temporary_dir" >&2
      ;;
  esac
}

make_temporary_dir() {
  temporary_dir=$(mktemp -d /tmp/resilience-gate-lab-ops.XXXXXX)
  chmod 700 "$temporary_dir"
  trap cleanup_temporary_dir EXIT
}

load_terraform_target() {
  # shellcheck source=../platform_setup_scripts/lib.sh
  source "$PLATFORM_DIR/lib.sh"
  load_config "$config_file"
  require_env PROJECT_ID REGION ZONE CLUSTER_NAME TF_STATE_BUCKET GITHUB_REPO GAR_REPO
  require_command terraform

  terraform_directory="$REPO_ROOT/gke_terraform"
  [ -d "$terraform_directory" ] || die "Terraform directory not found: $terraform_directory"

  terraform_target_args=(
    "-var=project_id=$PROJECT_ID"
    "-var=region=$REGION"
    "-var=zone=$ZONE"
    "-var=cluster_name=$CLUSTER_NAME"
    "-var=registry_repository_id=$GAR_REPO"
    "-var=github_repository=$GITHUB_REPO"
  )
}

terraform_in_target() {
  TF_DATA_DIR="$temporary_dir" terraform -chdir="$terraform_directory" "$@"
}

initialise_terraform() {
  terraform_in_target init \
    -input=false \
    -reconfigure \
    "-backend-config=bucket=$TF_STATE_BUCKET" \
    -backend-config=prefix=resilience-gate/terraform
}

create_destroy_plan() {
  local plan_file="${1:-}"
  # Retain Terraform's normal lock even for a read-only destroy plan. A
  # bounded wait prevents a concurrent apply from making the reviewed plan
  # stale while still avoiding an indefinite operator hang.
  local plan_args=(plan -destroy -input=false -lock=true -lock-timeout=5m -refresh=true)
  if [ -n "$plan_file" ]; then
    plan_args+=("-out=$plan_file")
  fi
  plan_args+=("${terraform_target_args[@]}")
  terraform_in_target "${plan_args[@]}"
}

validate_non_destructive_options() {
  if [ "$apply_requested" = true ] || [ -n "$confirmed_project" ] || [ "$destruction_acknowledged" = true ]; then
    die "Destruction acknowledgement options are valid only with the destroy command"
  fi
}

validate_non_status_scope() {
  [ "$status_scope" = all ] || die "--scope is valid only with the status command"
}

validate_destroy_options() {
  [ "$apply_requested" = true ] || die "destroy requires --apply"
  [ -n "$confirmed_project" ] || die "destroy requires --confirm-project PROJECT_ID"
  [ "$destruction_acknowledged" = true ] || \
    die "destroy requires --acknowledge-owned-testnet-lab-destruction"
  [ -t 0 ] || die "destroy requires an interactive terminal for project confirmation"
}

case "$command_name" in
  status)
    validate_non_destructive_options
    exec "$PLATFORM_DIR/07-verify.sh" --config "$config_file" --scope "$status_scope"
    ;;
  bootstrap-plan)
    validate_non_destructive_options
    validate_non_status_scope
    # The bootstrap orchestrator owns the phase ordering; the environment
    # override makes each of its mutation helpers print rather than execute.
    DRY_RUN=true exec "$PLATFORM_DIR/bootstrap.sh" --config "$config_file"
    ;;
  destroy-plan)
    validate_non_destructive_options
    validate_non_status_scope
    load_terraform_target
    make_temporary_dir
    log_step "Read-only Terraform destroy plan for owned testnet lab"
    initialise_terraform
    create_destroy_plan
    log_ok "Destroy plan completed; no infrastructure was changed"
    ;;
  destroy)
    # Reject insufficient consent before reading config, initialising Terraform,
    # or constructing a plan. A CI pipe is never treated as approval.
    validate_destroy_options
    validate_non_status_scope
    load_terraform_target
    [ "$confirmed_project" = "$PROJECT_ID" ] || \
      die "--confirm-project must exactly match configured PROJECT_ID"
    make_temporary_dir
    destroy_plan_file="$temporary_dir/destroy.tfplan"
    log_warn "Generating a fresh Terraform destroy plan for project $PROJECT_ID"
    initialise_terraform
    create_destroy_plan "$destroy_plan_file"
    printf '[CONFIRM] Type %s to apply this exact destroy plan: ' "$PROJECT_ID" >&2
    IFS= read -r typed_project
    [ "$typed_project" = "$PROJECT_ID" ] || die "Project confirmation did not match; destroy plan was not applied"
    # Apply only the just-created plan. Do not override Terraform's deletion
    # protection input: a protected cluster needs a separate reviewed workflow.
    terraform_in_target apply -input=false "$destroy_plan_file"
    log_ok "Terraform applied the explicitly confirmed destroy plan"
    ;;
esac
